// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using NpgsqlTypes;
using OrdoWiki.Data;

#nullable disable

namespace OrdoWiki.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260704034753_StripHtmlFromSearchVectors")]
    partial class StripHtmlFromSearchVectors
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text")
                        .HasColumnName("concurrency_stamp");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_name");

                    b.HasKey("Id")
                        .HasName("pk_roles");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("ix_roles_normalized_name");

                    b.ToTable("roles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text")
                        .HasColumnName("claim_type");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text")
                        .HasColumnName("claim_value");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("role_id");

                    b.HasKey("Id")
                        .HasName("pk_role_claims");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_role_claims_role_id");

                    b.ToTable("role_claims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text")
                        .HasColumnName("claim_type");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text")
                        .HasColumnName("claim_value");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_user_claims");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_user_claims_user_id");

                    b.ToTable("user_claims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("login_provider");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("provider_key");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text")
                        .HasColumnName("provider_display_name");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.HasKey("LoginProvider", "ProviderKey")
                        .HasName("pk_user_logins");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_user_logins_user_id");

                    b.ToTable("user_logins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserPasskey<string>", b =>
                {
                    b.Property<byte[]>("CredentialId")
                        .HasMaxLength(1024)
                        .HasColumnType("bytea")
                        .HasColumnName("credential_id");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.HasKey("CredentialId")
                        .HasName("pk_user_passkeys");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_user_passkeys_user_id");

                    b.ToTable("user_passkeys", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.Property<string>("RoleId")
                        .HasColumnType("text")
                        .HasColumnName("role_id");

                    b.HasKey("UserId", "RoleId")
                        .HasName("pk_user_roles");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_user_roles_role_id");

                    b.ToTable("user_roles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("login_provider");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("name");

                    b.Property<string>("Value")
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.HasKey("UserId", "LoginProvider", "Name")
                        .HasName("pk_user_tokens");

                    b.ToTable("user_tokens", (string)null);
                });

            modelBuilder.Entity("OrdoWiki.Data.Entities.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer")
                        .HasColumnName("access_failed_count");

                    b.Property<string>("AvatarPath")
                        .HasColumnType("text")
                        .HasColumnName("avatar_path");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text")
                        .HasColumnName("concurrency_stamp");

                    b.Property<string>("DisplayName")
                        .HasColumnType("text")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("email_confirmed");

                    b.Property<bool>("IsGhost")
                        .HasColumnType("boolean")
                        .HasColumnName("is_ghost");

                    b.Property<bool>("IsPasswordResetRequired")
                        .HasColumnType("boolean")
                        .HasColumnName("is_password_reset_required");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("lockout_enabled");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lockout_end");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_email");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_user_name");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("phone_number");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("phone_number_confirmed");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text")
                        .HasColumnName("security_stamp");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("two_factor_enabled");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("user_name");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("ix_users_normalized_email");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("ix_users_normalized_user_name");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("OrdoWiki.Data.Entities.Banner", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Alt")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("alt");

                    b.Property<string>("LinkUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("link_url");

                    b.Property<Guid?>("MediaAssetId")
                        .HasColumnType("uuid")
                        .HasColumnName("media_asset_id");

                    b.Property<int>("SlotIndex")
                        .HasColumnType("integer")
                        .HasColumnName("slot_index");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedById")
                        .HasColumnType("text")
                        .HasColumnName("updated_by_id");

                    b.HasKey("Id")
                        .HasName("pk_banners");

                    b.HasIndex("MediaAssetId")
                        .HasDatabaseName("ix_banners_media_asset_id");

                    b.HasIndex("SlotIndex")
                        .IsUnique()
                        .HasDatabaseName("ix_banners_slot_index");

                    b.HasIndex("UpdatedById")
                        .HasDatabaseName("ix_banners_updated_by_id");

                    b.ToTable("banners", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("b1000000-0000-0000-0000-000000000001"),
                            SlotIndex = 1,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("b1000000-0000-0000-0000-000000000002"),
                            SlotIndex = 2,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("b1000000-0000-0000-0000-000000000003"),
                            SlotIndex = 3,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("b1000000-0000-0000-0000-000000000004"),
                            SlotIndex = 4,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("OrdoWiki.Data.Entities.Character", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("ContentFormat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("content_format");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("MarkdownBody")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("markdown_body");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name");

                    b.Property<string>("OwnerId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("owner_id");

                    b.Property<NpgsqlTsVector>("SearchVector")
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("tsvector")
                        .HasColumnName("search_vector")
                        .HasComputedColumnSql("setweight(to_tsvector('english', name), 'A') || setweight(to_tsvector('english', coalesce(summary, '')), 'B') || setweight(to_tsvector('english', regexp_replace(coalesce(markdown_body, ''), '<[^>]+>', ' ', 'g')), 'C')", true);

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("slug");

                    b.Property<string>("Summary")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("summary");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_characters");

                    b.HasIndex("OwnerId")
                        .HasDatabaseName("ix_characters_owner_id");

                    b.HasIndex("SearchVector")
                        .HasDatabaseName("ix_characters_search_vector");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("SearchVector"), "GIN");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_characters_slug");

                    b.ToTable("characters", (string)null);
                });

            modelBuilder.Entity("OrdoWiki.Data.Entities.CharacterImage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Caption")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("caption");

                    b.Property<Guid>("CharacterId")
                        .HasColumnType("uuid")
                        .HasColumnName("character_id");

                    b.Property<Guid>("MediaAssetId")
                        .HasColumnType("uuid")
                        .HasColumnName("media_asset_id");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("integer")
                        .HasColumnName("order_index");

                    b.HasKey("Id")
                        .HasName("pk_character_images");

                    b.HasIndex("MediaAssetId")
                        .HasDatabaseName("ix_character_images_media_asset_id");

                    b.HasIndex("CharacterId", "OrderIndex")
                        .HasDatabaseName("ix_character_images_character_id_order_index");

                    b.ToTable("character_images", (string)null);
                });

            modelBuilder.Entity("OrdoWiki.Data.Entities.CharacterTag", b =>
                {
                    b.Property<Guid>("CharacterId")
                        .HasColumnType("uuid")
                        .HasColumnName("character_id");

                    b.Property<Guid>("TagId")
                        .HasColumnType("uuid")
                        .HasColumnName("tag_id");

                    b.HasKey("CharacterId", "TagId")
                        .HasName("pk_character_tags");

                    b.HasIndex("TagId")
                        .HasDatabaseName("ix_character_tags_tag_id");

                    b.ToTable("character_tags", (string)null);
                });

            modelBuilder.Entity("OrdoWiki.Data.Entities.CustomThemeVariable", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("name");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.HasKey("Id")
                        .HasName("pk_custom_theme_variables");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_custom_theme_variables_name");

                    b.ToTable("custom_theme_variables", (string)null);
                });

            modelBuilder.Entity("OrdoWiki.Data.Entities.HomePage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BioMarkdown")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("bio_markdown");

                    b.Property<Guid?>("FeaturedLogId")
                        .HasColumnType("uuid")
                        .HasColumnName("featured_log_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedById")
                        .HasColumnType("text")
                        .HasColumnName("updated_by_id");

                    b.HasKey("Id")
                        .HasName("pk_home_pages");

                    b.HasIndex("FeaturedLogId")
                        .HasDatabaseName("ix_home_pages_featured_log_id");

                    b.HasIndex("UpdatedById")
                        .HasDatabaseName("ix_home_pages_updated_by_id");

                    b.ToTable("home_pages", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("a1000000-0000-0000-0000-000000000001"),
                            BioMarkdown = "",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("OrdoWiki.Data.Entities.InviteCode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AssignedRole")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("assigned_role");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedByUserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("created_by_user_id");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<DateTimeOffset?>("RedeemedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("redeemed_at");

                    b.Property<string>("RedeemedByUserId")
                        .HasColumnType("text")
                        .HasColumnName("redeemed_by_user_id");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<string>("RevokedByUserId")
                        .HasColumnType("text")
                        .HasColumnName("revoked_by_user_id");

                    b.HasKey("Id")
                        .HasName("pk_invite_codes");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_invite_codes_code");

                    b.ToTable("invite_codes", (string)null);
                });

            modelBuilder.Entity("OrdoWiki.Data.Entities.MandoEra", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AnchorYear")
                        .HasColumnType("integer")
                        .HasColumnName("anchor_year");

                    b.Property<int>("Direction")
                        .HasColumnType("integer")
                        .HasColumnName("direction");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("name");

                    b.Property<string>("ShortCode")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("short_code");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.HasKey("Id")
                        .HasName("pk_mando_eras");

                    b.HasIndex("AnchorYear")
                        .HasDatabaseName("ix_mando_eras_anchor_year");

                    b.HasIndex("ShortCode")
                        .IsUnique()
                        .HasDatabaseName("ix_mando_eras_short_code");

                    b.ToTable("mando_eras", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("e1a0e1a0-0000-0000-0000-000000000001"),
                            AnchorYear = 0,
                            Direction = 1,
                            Name = "Before Civil War",
                            ShortCode = "BCW",
                            SortOrder = 0
                        },
                        new
                        {
                            Id = new Guid("e1a0e1a0-0000-0000-0000-000000000002"),
                            AnchorYear = 0,
                            Direction = 0,
                            Name = "After Civil War",
                            ShortCode = "ACW",
                            SortOrder = 1
                        });
                });

            modelBuilder.Entity("OrdoWiki.Data.Entities.MandoMonth", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("MonthIndex")
                        .HasColumnType("integer")
                        .HasColumnName("month_index");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_mando_months");

                    b.HasIndex("MonthIndex")
                        .IsUnique()
                        .HasDatabaseName("ix_mando_months_month_index");

                    b.ToTable("mando_months", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("a1c0c0a0-0001-0000-0000-000000000001"),
                            MonthIndex = 1,
                            Name = "Vhett'yc"
                        },
                        new
                        {
                            Id = new Guid("a1c0c0a0-0002-0000-0000-000000000002"),
                            MonthIndex = 2,
                            Name = "Beskar'yc"
                        },
                        new
                        {
                            Id = new Guid("a1c0c0a0-0003-0000-0000-000000000003"),
                            MonthIndex = 3,
                            Name = "Verd'yc"
                        },
                        new
                        {
                            Id = new Guid("a1c0c0a0-0004-0000-0000-000000000004"),
                            MonthIndex = 4,
                            Name = "Kote'yc"
                        },
                        new
                        {
                            Id = new Guid("a1c0c0a0-0005-0000-0000-000000000005"),
                            MonthIndex = 5,
                            Name = "Manda'yc"
                        },
                        new
                        {
                            Id = new Guid("a1c0c0a0-0006-0000-0000-000000000006"),
                            MonthIndex = 6,
                            Name = "Aliit'yc"
                        },
                        new
                        {
                            Id = new Guid("a1c0c0a0-0007-0000-0000-000000000007"),
                            MonthIndex = 7,
                            Name = "Ka'ra'yc"
                        },
                        new
                        {
                            Id = new Guid("a1c0c0a0-0008-0000-0000-000000000008"),
                            MonthIndex = 8,
                            Name = "Aay'han'yc"
                        },
                        new
                        {
                            Id = new Guid("a1c0c0a0-0009-0000-0000-000000000009"),
                            MonthIndex = 9,
                            Name = "Akaan'yc"
                        },
                        new
                        {
                            Id = new Guid("a1c0c0a0-0010-0000-0000-000000000010"),
                            MonthIndex = 10,
                            Name = "Mando'yc"
                        },
                        new
                        {
                            Id = new Guid("a1c0c0a0-0011-0000-0000-000000000011"),
                            MonthIndex = 11,
                            Name = "Resol'yc"
                        },
                        new
                        {
                            Id = new Guid("a1c0c0a0-0012-0000-0000-000000000012"),
                            MonthIndex = 12,
                            Name = "Buir'yc"
                        });
                });

            modelBuilder.Entity("OrdoWiki.Data.Entities.MediaAsset", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("content_type");

                    b.Property<int?>("Height")
                        .HasColumnType("integer")
                        .HasColumnName("height");

                    b.Property<string>("OriginalName")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("character varying(260)")
                        .HasColumnName("original_name");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("size_bytes");

                    b.Property<Guid?>("SourceId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_id");

                    b.Property<int>("SourceType")
                        .HasColumnType("integer")
                        .HasColumnName("source_type");

                    b.Property<string>("StoragePath")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("storage_path");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("uploaded_at");

                    b.Property<string>("UploadedById")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("uploaded_by_id");

                    b.Property<int?>("Width")
                        .HasColumnType("integer")
                        .HasColumnName("width");

                    b.HasKey("Id")
                        .HasName("pk_media_assets");

                    b.HasIndex("UploadedAt")
                        .HasDatabaseName("ix_media_assets_uploaded_at");

                    b.HasIndex("UploadedById")
                        .HasDatabaseName("ix_media_assets_uploaded_by_id");

                    b.HasIndex("SourceType", "UploadedAt")
                        .HasDatabaseName("ix_media_assets_source_type_uploaded_at");

                    b.ToTable("media_assets", (string)null);
                });

            modelBuilder.Entity("OrdoWiki.Data.Entities.MediaAssetTag", b =>
                {
                    b.Property<Guid>("MediaAssetId")
                        .HasColumnType("uuid")
                        .HasColumnName("media_asset_id");

                    b.Property<Guid>("TagId")
                        .HasColumnType("uuid")
                        .HasColumnName("tag_id");

                    b.HasKey("MediaAssetId", "TagId")
                        .HasName("pk_media_asset_tags");

                    b.HasIndex("TagId")
                        .HasDatabaseName("ix_media_asset_tags_tag_id");

                    b.ToTable("media_asset_tags", (string)null);
                });

            modelBuilder.Entity("OrdoWiki.Data.Entities.PageRevision", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("ContentFormat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("content_format");

                    b.Property<string>("EditSummary")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("edit_summary");

                    b.Property<DateTime>("EditedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("edited_at");

                    b.Property<string>("EditedById")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("edited_by_id");

                    b.Property<string>("MarkdownBody")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("markdown_body");

                    b.Property<Guid>("PageId")
                        .HasColumnType("uuid")
                        .HasColumnName("page_id");

                    b.Property<NpgsqlTsVector>("SearchVector")
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("tsvector")
                        .HasColumnName("search_vector")
                        .HasComputedColumnSql("to_tsvector('english', regexp_replace(markdown_body, '<[^>]+>', ' ', 'g'))", true);

                    b.HasKey("Id")
                        .HasName("pk_page_revisions");

                    b.HasIndex("EditedById")
                        .HasDatabaseName("ix_page_revisions_edited_by_id");

                    b.HasIndex("PageId")
                        .HasDatabaseName("ix_page_revisions_page_id");

                    b.HasIndex("SearchVector")
                        .HasDatabaseName("ix_page_revisions_search_vector");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("SearchVector"), "GIN");

                    b.ToTable("page_revisions", (string)null);
                });

            modelBuilder.Entity("OrdoWiki.Data.Entities.RelatedItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("SourceId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_id");

                    b.Property<int>("SourceKind")
                        .HasColumnType("integer")
                        .HasColumnName("source_kind");

                    b.Property<Guid>("TargetId")
                        .HasColumnType("uuid")
                        .HasColumnName("target_id");

                    b.Property<int>("TargetKind")
                        .HasColumnType("integer")
                        .HasColumnName("target_kind");

                    b.HasKey("Id")
                        .HasName("pk_related_items");

                    b.HasIndex("TargetKind", "TargetId")
                        .HasDatabaseName("ix_related_items_target_kind_target_id");

                    b.HasIndex("SourceKind", "SourceId", "TargetKind", "TargetId")
                        .IsUnique()
                        .HasDatabaseName("ix_related_items_source_kind_source_id_target_kind_target_id");

                    b.ToTable("related_items", (string)null);
                });

            modelBuilder.Entity("OrdoWiki.Data.Entities.SiteTheme", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CustomValuesJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("custom_values_json");

                    b.Property<Guid?>("DarkBackgroundAssetId")
                        .HasColumnType("uuid")
                        .HasColumnName("dark_background_asset_id");

                    b.Property<string>("DarkPaletteJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("dark_palette_json");

                    b.Property<Guid?>("LightBackgroundAssetId")
                        .HasColumnType("uuid")
                        .HasColumnName("light_background_asset_id");

                    b.Property<string>("LightPaletteJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("light_palette_json");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedById")
                        .HasColumnType("text")
                        .HasColumnName("updated_by_id");

                    b.HasKey("Id")
                        .HasName("pk_site_themes");

                    b.HasIndex("DarkBackgroundAssetId")
                        .HasDatabaseName("ix_site_themes_dark_background_asset_id");

                    b.HasIndex("LightBackgroundAssetId")
                        .HasDatabaseName("ix_site_themes_light_background_asset_id");

                    b.HasIndex("UpdatedById")
                        .HasDatabaseName("ix_site_themes_updated_by_id");

                    b.ToTable("site_themes", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("51000000-0000-0000-0000-000000000001"),
                            CustomValuesJson = "{}",
                            DarkPaletteJson = "{}",
                            LightPaletteJson = "{}",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("OrdoWiki.Data.Entities.Tag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedById")
                        .HasColumnType("text")
                        .HasColumnName("created_by_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("name");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("slug");

                    b.HasKey("Id")
                        .HasName("pk_tags");

                    b.HasIndex("CreatedById")
                        .HasDatabaseName("ix_tags_created_by_id");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_tags_slug");

                    b.ToTable("tags", (string)null);
                });

            modelBuilder.Entity("OrdoWiki.Data.Entities.TimelineEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("ContentFormat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("content_format");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedById")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("created_by_id");

                    b.Property<string>("DisplayOverride")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("display_override");

                    b.Property<long>("EpochDayNumber")
                        .HasColumnType("bigint")
                        .HasColumnName("epoch_day_number");

                    b.Property<int?>("MandoDay")
                        .HasColumnType("integer")
                        .HasColumnName("mando_day");

                    b.Property<int?>("MandoMonth")
                        .HasColumnType("integer")
                        .HasColumnName("mando_month");

                    b.Property<int>("MandoYear")
                        .HasColumnType("integer")
                        .HasColumnName("mando_year");

                    b.Property<string>("MarkdownBody")
                        .HasColumnType("text")
                        .HasColumnName("markdown_body");

                    b.Property<NpgsqlTsVector>("SearchVector")
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("tsvector")
                        .HasColumnName("search_vector")
                        .HasComputedColumnSql("setweight(to_tsvector('english', title), 'A') || setweight(to_tsvector('english', coalesce(summary, '')), 'B') || setweight(to_tsvector('english', regexp_replace(coalesce(markdown_body, ''), '<[^>]+>', ' ', 'g')), 'C')", true);

                    b.Property<string>("Summary")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("summary");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_timeline_events");

                    b.HasIndex("CreatedById")
                        .HasDatabaseName("ix_timeline_events_created_by_id");

                    b.HasIndex("EpochDayNumber")
                        .HasDatabaseName("ix_timeline_events_epoch_day_number");

                    b.HasIndex("SearchVector")
                        .HasDatabaseName("ix_timeline_events_search_vector");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("SearchVector"), "GIN");

                    b.ToTable("timeline_events", (string)null);
                });

            modelBuilder.Entity("OrdoWiki.Data.Entities.TimelineEventTag", b =>
                {
                    b.Property<Guid>("TimelineEventId")
                        .HasColumnType("uuid")
                        .HasColumnName("timeline_event_id");

                    b.Property<Guid>("TagId")
                        .HasColumnType("uuid")
                        .HasColumnName("tag_id");

                    b.HasKey("TimelineEventId", "TagId")
                        .HasName("pk_timeline_event_tags");

                    b.HasIndex("TagId")
                        .HasDatabaseName("ix_timeline_event_tags_tag_id");

                    b.ToTable("timeline_event_tags", (string)null);
                });

            modelBuilder.Entity("OrdoWiki.Data.Entities.WikiPage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedById")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("created_by_id");

                    b.Property<Guid?>("CurrentRevisionId")
                        .HasColumnType("uuid")
                        .HasColumnName("current_revision_id");

                    b.Property<NpgsqlTsVector>("SearchVector")
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("tsvector")
                        .HasColumnName("search_vector")
                        .HasComputedColumnSql("setweight(to_tsvector('english', title), 'A') || setweight(to_tsvector('english', coalesce(summary, '')), 'B')", true);

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("slug");

                    b.Property<string>("Summary")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("summary");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_wiki_pages");

                    b.HasIndex("CreatedById")
                        .HasDatabaseName("ix_wiki_pages_created_by_id");

                    b.HasIndex("CurrentRevisionId")
                        .IsUnique()
                        .HasDatabaseName("ix_wiki_pages_current_revision_id");

                    b.HasIndex("SearchVector")
                        .HasDatabaseName("ix_wiki_pages_search_vector");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("SearchVector"), "GIN");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_wiki_pages_slug");

                    b.ToTable("wiki_pages", (string)null);
                });

            modelBuilder.Entity("OrdoWiki.Data.Entities.WikiPageTag", b =>
                {
                    b.Property<Guid>("PageId")
                        .HasColumnType("uuid")
                        .HasColumnName("page_id");

                    b.Property<Guid>("TagId")
                        .HasColumnType("uuid")
                        .HasColumnName("tag_id");

                    b.HasKey("PageId", "TagId")
                        .HasName("pk_wiki_page_tags");

                    b.HasIndex("TagId")
                        .HasDatabaseName("ix_wiki_page_tags_tag_id");

                    b.ToTable("wiki_page_tags", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_role_claims_roles_role_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("OrdoWiki.Data.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_claims_users_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("OrdoWiki.Data.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_logins_users_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserPasskey<string>", b =>
                {
                    b.HasOne("OrdoWiki.Data.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_passkeys_users_user_id");

                    b.OwnsOne("Microsoft.AspNetCore.Identity.IdentityPasskeyData", "Data", b1 =>
                        {
                            b1.Property<byte[]>("IdentityUserPasskeyCredentialId");

                            b1.Property<byte[]>("AttestationObject")
                                .IsRequired();

                            b1.Property<byte[]>("ClientDataJson")
                                .IsRequired();

                            b1.Property<DateTimeOffset>("CreatedAt");

                            b1.Property<bool>("IsBackedUp");

                            b1.Property<bool>("IsBackupEligible");

                            b1.Property<bool>("IsUserVerified");

                            b1.Property<string>("Name");

                            b1.Property<byte[]>("PublicKey")
                                .IsRequired();

                            b1.Property<long>("SignCount");

                            b1.PrimitiveCollection<string>("Transports");

                            b1.HasKey("IdentityUserPasskeyCredentialId");

                            b1.ToTable("user_passkeys");

                            b1
                                .ToJson("data")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("IdentityUserPasskeyCredentialId")
                                .HasConstraintName("fk_asp_net_user_passkeys_asp_net_user_passkeys_credential_id");
                        });

                    b.Navigation("Data")
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_roles_roles_role_id");

                    b.HasOne("OrdoWiki.Data.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_roles_users_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("OrdoWiki.Data.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_tokens_users_user_id");
                });

            modelBuilder.Entity("OrdoWiki.Data.Entities.Banner", b =>
                {
                    b.HasOne("OrdoWiki.Data.Entities.MediaAsset", "MediaAsset")
                        .WithMany()
                        .HasForeignKey("MediaAssetId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_banners_media_assets_media_asset_id");

                    b.HasOne("OrdoWiki.Data.Entities.ApplicationUser", "UpdatedBy")
                        .WithMany()
                        .HasForeignKey("UpdatedById")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_banners_users_updated_by_id");

                    b.Navigation("MediaAsset");

                    b.Navigation("UpdatedBy");
                });

            modelBuilder.Entity("OrdoWiki.Data.Entities.Character", b =>
                {
                    b.HasOne("OrdoWiki.Data.Entities.ApplicationUser", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_characters_users_owner_id");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("OrdoWiki.Data.Entities.CharacterImage", b =>
                {
                    b.HasOne("OrdoWiki.Data.Entities.Character", "Character")
                        .WithMany("Images")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_character_images_characters_character_id");

                    b.HasOne("OrdoWiki.Data.Entities.MediaAsset", "MediaAsset")
                        .WithMany()
                        .HasForeignKey("MediaAssetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_character_images_media_assets_media_asset_id");

                    b.Navigation("Character");

                    b.Navigation("MediaAsset");
                });

            modelBuilder.Entity("OrdoWiki.Data.Entities.CharacterTag", b =>
                {
                    b.HasOne("OrdoWiki.Data.Entities.Character", "Character")
                        .WithMany()
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_character_tags_characters_character_id");

                    b.HasOne("OrdoWiki.Data.Entities.Tag", "Tag")
                        .WithMany()
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_character_tags_tags_tag_id");

                    b.Navigation("Character");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("OrdoWiki.Data.Entities.HomePage", b =>
                {
                    b.HasOne("OrdoWiki.Data.Entities.WikiPage", "FeaturedLog")
                        .WithMany()
                        .HasForeignKey("FeaturedLogId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_home_pages_wiki_pages_featured_log_id");

                    b.HasOne("OrdoWiki.Data.Entities.ApplicationUser", "UpdatedBy")
                        .WithMany()
                        .HasForeignKey("UpdatedById")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_home_pages_users_updated_by_id");

                    b.Navigation("FeaturedLog");

                    b.Navigation("UpdatedBy");
                });

            modelBuilder.Entity("OrdoWiki.Data.Entities.MediaAsset", b =>
                {
                    b.HasOne("OrdoWiki.Data.Entities.ApplicationUser", "UploadedBy")
                        .WithMany()
                        .HasForeignKey("UploadedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_media_assets_users_uploaded_by_id");

                    b.Navigation("UploadedBy");
                });

            modelBuilder.Entity("OrdoWiki.Data.Entities.MediaAssetTag", b =>
                {
                    b.HasOne("OrdoWiki.Data.Entities.MediaAsset", "MediaAsset")
                        .WithMany()
                        .HasForeignKey("MediaAssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_media_asset_tags_media_assets_media_asset_id");

                    b.HasOne("OrdoWiki.Data.Entities.Tag", "Tag")
                        .WithMany()
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_media_asset_tags_tags_tag_id");

                    b.Navigation("MediaAsset");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("OrdoWiki.Data.Entities.PageRevision", b =>
                {
                    b.HasOne("OrdoWiki.Data.Entities.ApplicationUser", "Editor")
                        .WithMany()
                        .HasForeignKey("EditedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_page_revisions_users_edited_by_id");

                    b.HasOne("OrdoWiki.Data.Entities.WikiPage", "Page")
                        .WithMany("Revisions")
                        .HasForeignKey("PageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_page_revisions_wiki_pages_page_id");

                    b.Navigation("Editor");

                    b.Navigation("Page");
                });

            modelBuilder.Entity("OrdoWiki.Data.Entities.SiteTheme", b =>
                {
                    b.HasOne("OrdoWiki.Data.Entities.MediaAsset", "DarkBackgroundAsset")
                        .WithMany()
                        .HasForeignKey("DarkBackgroundAssetId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_site_themes_media_assets_dark_background_asset_id");

                    b.HasOne("OrdoWiki.Data.Entities.MediaAsset", "LightBackgroundAsset")
                        .WithMany()
                        .HasForeignKey("LightBackgroundAssetId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_site_themes_media_assets_light_background_asset_id");

                    b.HasOne("OrdoWiki.Data.Entities.ApplicationUser", "UpdatedBy")
                        .WithMany()
                        .HasForeignKey("UpdatedById")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_site_themes_users_updated_by_id");

                    b.Navigation("DarkBackgroundAsset");

                    b.Navigation("LightBackgroundAsset");

                    b.Navigation("UpdatedBy");
                });

            modelBuilder.Entity("OrdoWiki.Data.Entities.Tag", b =>
                {
                    b.HasOne("OrdoWiki.Data.Entities.ApplicationUser", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_tags_users_created_by_id");

                    b.Navigation("CreatedBy");
                });

            modelBuilder.Entity("OrdoWiki.Data.Entities.TimelineEvent", b =>
                {
                    b.HasOne("OrdoWiki.Data.Entities.ApplicationUser", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_timeline_events_users_created_by_id");

                    b.Navigation("CreatedBy");
                });

            modelBuilder.Entity("OrdoWiki.Data.Entities.TimelineEventTag", b =>
                {
                    b.HasOne("OrdoWiki.Data.Entities.Tag", "Tag")
                        .WithMany()
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_timeline_event_tags_tags_tag_id");

                    b.HasOne("OrdoWiki.Data.Entities.TimelineEvent", "TimelineEvent")
                        .WithMany()
                        .HasForeignKey("TimelineEventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_timeline_event_tags_timeline_events_timeline_event_id");

                    b.Navigation("Tag");

                    b.Navigation("TimelineEvent");
                });

            modelBuilder.Entity("OrdoWiki.Data.Entities.WikiPage", b =>
                {
                    b.HasOne("OrdoWiki.Data.Entities.ApplicationUser", "Creator")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_wiki_pages_users_created_by_id");

                    b.HasOne("OrdoWiki.Data.Entities.PageRevision", "CurrentRevision")
                        .WithOne()
                        .HasForeignKey("OrdoWiki.Data.Entities.WikiPage", "CurrentRevisionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_wiki_pages_page_revisions_current_revision_id");

                    b.Navigation("Creator");

                    b.Navigation("CurrentRevision");
                });

            modelBuilder.Entity("OrdoWiki.Data.Entities.WikiPageTag", b =>
                {
                    b.HasOne("OrdoWiki.Data.Entities.WikiPage", "Page")
                        .WithMany()
                        .HasForeignKey("PageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_wiki_page_tags_wiki_pages_page_id");

                    b.HasOne("OrdoWiki.Data.Entities.Tag", "Tag")
                        .WithMany()
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_wiki_page_tags_tags_tag_id");

                    b.Navigation("Page");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("OrdoWiki.Data.Entities.Character", b =>
                {
                    b.Navigation("Images");
                });

            modelBuilder.Entity("OrdoWiki.Data.Entities.WikiPage", b =>
                {
                    b.Navigation("Revisions");
                });
#pragma warning restore 612, 618
        }
    }
}
